apiVersion: v1
kind: Service
metadata:
  name: adversarial-detection-service
spec:
  selector:
    app: adversarial-detection
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
